name: Build Android App

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      # Tự động sửa lỗi thiếu thư mục Android
      - name: Fix Android Project
        run: |
          flutter create . --org com.adbmaster
          flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
      
      # Upload file lên để tải về
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ADB-Master-Final
          path: build/app/outputs/flutter-apk/app-release.apk
