name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      # SỬA LỖI Ở ĐÂY: Thêm --project-name adb_master để không bị lỗi chữ hoa
      - name: Fix Android Project
        run: |
          flutter create --project-name adb_master . --org com.adbmaster
          flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ADB-Master-Fixed
          path: build/app/outputs/flutter-apk/app-release.apk

